---
version-template: 'v$MAJOR.$MINOR'
name-template: 'v$NEXT_MINOR_VERSION 🌈'
tag-template: 'v$NEXT_MINOR_VERSION'
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## What’s Changed

  $CHANGES
...
